# Generated by Django 5.2 on 2026-06-17 23:05

import django.db.models.deletion
import journals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название журнала')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=journals.models.template_upload_path, verbose_name='Файл шаблона')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='journals.journal', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Версия шаблона',
                'verbose_name_plural': 'Версии шаблонов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
