# Generated by Django 5.2 on 2026-06-17 23:05

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_html', models.TextField(blank=True, verbose_name='HTML-содержимое')),
                ('file_docx', models.FileField(blank=True, null=True, upload_to=articles.models.article_docx_path, verbose_name='Файл .docx')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to=articles.models.article_pdf_path, verbose_name='Файл .pdf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Название рус.')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Название англ.')),
                ('udc', models.CharField(blank=True, max_length=50, verbose_name='УДК')),
                ('annotation_ru', models.TextField(blank=True, verbose_name='Аннотация рус.')),
                ('annotation_en', models.TextField(blank=True, verbose_name='Аннотация англ.')),
                ('keywords_ru', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова рус.')),
                ('keywords_en', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова англ.')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('order_num', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
    ]
