# Generated by Django 5.2 on 2026-06-17 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role__in': ['student', 'teacher']}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metadata',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='articles.article'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journal', verbose_name='Журнал'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_articles', to=settings.AUTH_USER_MODEL, verbose_name='Научный руководитель'),
        ),
        migrations.AddField(
            model_name='reference',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='articles.article'),
        ),
        migrations.AddConstraint(
            model_name='articleauthor',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='unique_article_author'),
        ),
    ]
