# Generated by Django 5.2 on 2026-06-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='gost_string',
            field=models.TextField(blank=True, verbose_name='Библиографическая запись (ГОСТ)'),
        ),
        migrations.AddField(
            model_name='reference',
            name='source_type',
            field=models.CharField(choices=[('print', 'Печатный источник'), ('electronic', 'Электронный ресурс')], default='print', max_length=20, verbose_name='Тип источника'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='annotation_en',
            field=models.TextField(blank=True, verbose_name='Аннотация на английском'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='annotation_ru',
            field=models.TextField(blank=True, verbose_name='Аннотация на русском'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова на английском'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='keywords_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова на русском'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название статьи на английском'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название статьи на русском'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(blank=True, max_length=100, verbose_name='DOI'),
        ),
    ]
