# Generated by Django 5.2 on 2026-06-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_course_user_department_user_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('', '— не выбран —'), ('бакалавриат', 'бакалавриат'), ('специалитет', 'специалитет'), ('магистратура', 'магистратура'), ('аспирантура', 'аспирантура')], max_length=50, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
    ]
